<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>DemoProject</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <BaseOutputPath>temp/bin</BaseOutputPath>
    <BaseIntermediateOutputPath>temp/obj</BaseIntermediateOutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="data/Scripts/Arrow.cs">
      <Link>Scripts/Arrow.cs</Link>
    </Compile>
    <Compile Include="data/Scripts/CharacterAnimator.cs">
      <Link>Scripts/CharacterAnimator.cs</Link>
    </Compile>
    <Compile Include="data/Scripts/CharacterController.cs">
      <Link>Scripts/CharacterController.cs</Link>
    </Compile>
    <Compile Include="data/Scripts/CharacterShooter.cs">
      <Link>Scripts/CharacterShooter.cs</Link>
    </Compile>
    <Compile Include="data/Scripts/HitEffect.cs">
      <Link>Scripts/HitEffect.cs</Link>
    </Compile>
    <Compile Include="data/Scripts/JumpPlatform.cs">
      <Link>Scripts/JumpPlatform.cs</Link>
    </Compile>
    <Compile Include="data/Scripts/TextTest.cs">
      <Link>Scripts/TextTest.cs</Link>
    </Compile>
    <Compile Include="data/UI/Scripts/BaseMenu.cs">
      <Link>UI/Scripts/BaseMenu.cs</Link>
    </Compile>
    <Compile Include="data/UI/Scripts/GameMenu.cs">
      <Link>UI/Scripts/GameMenu.cs</Link>
    </Compile>
    <Compile Include="data/UI/Scripts/GameUI.cs">
      <Link>UI/Scripts/GameUI.cs</Link>
    </Compile>
    <Compile Include="data/UI/Scripts/LobbyUI.cs">
      <Link>UI/Scripts/LobbyUI.cs</Link>
    </Compile>
    <Compile Include="data/UI/Scripts/MainMenu.cs">
      <Link>UI/Scripts/MainMenu.cs</Link>
    </Compile>
    <Compile Include="data/UI/Scripts/SettingsMenu.cs">
      <Link>UI/Scripts/SettingsMenu.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="engine-script.dll">
      <HintPath>C:/Workspace/github/UnravelEngine/UnravelEngine/build/RelWithDebInfo/bin/data/engine/compiled/engine-script.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
